use_frameworks!
platform :ios, '9.0'

target 'LDOConditionalDateFormatter_Example' do
  pod "LDOConditionalDateFormatter", :path => "../"
end

target 'LDOConditionalDateFormatter_Tests' do
  pod "LDOConditionalDateFormatter", :path => "../" 
end
