source 'https://github.com/CocoaPods/Specs.git'

target 'LDOConditionalDateFormatter_Example', :exclusive => true do
  pod "LDOConditionalDateFormatter", :path => "../"
end

target 'LDOConditionalDateFormatter_Tests', :exclusive => true do
  pod "LDOConditionalDateFormatter", :path => "../" 
end
