source 'https://github.com/CocoaPods/Specs.git'

target 'SLConditionalDateFormatter_Example', :exclusive => true do
  pod "SLConditionalDateFormatter", :path => "../"
end

target 'SLConditionalDateFormatter_Tests', :exclusive => true do
  pod "SLConditionalDateFormatter", :path => "../"

  
end
